### ISSUE TITLE
Logging and Stack Tracing In Elixir/Erlang

### ISSUE THREAD

**Issue by nelsonic** [dwyl/learn-elixir#149]
At present we do not have a section in this guide on Logging or Error tracing.
This is an omission as it is an important step in building apps that are maintainable.

This looks like a good starting point: https://timber.io/blog/the-ultimate-guide-to-logging-in-elixir/
PDF Snapshot: [The-Ultimate-Guide-To-Logging-In-Elixir.pdf](https://github.com/dwyl/learn-elixir/files/4006650/The-Ultimate-Guide-To-Logging-In-Elixir.pdf)

# Todo

+ [ ] do a bunch of research into stack tracing and logging in Elixir
+ [ ] Figure out how to do logging on Heroku (_and any other relevant IaaS/PaaS provider_)
+ [ ] Write it up!
