### ISSUE TITLE
Sobelow security-focused static analysis tool for Phoenix

### ISSUE THREAD

**Issue by nelsonic** [dwyl/learn-elixir#159]
Was recently reminded of [`sobelow`](https://hex.pm/packages/sobelow) when reading @samhstn's PR https://github.com/samhstn/samhstn/pull/96 💡 
We haven't used it in any of our projects but it's come a _long_ way since we last looked at it, 📈 
and it's worth considering for our [`auth`](https://github.com/dwyl/auth) project which is a Phoenix App and can use some security analysis. 🔐 

# Todo

+ [ ] Add `{:sobelow, "~> 0.10.5"}` to [`auth/mix.exs`](https://github.com/dwyl/auth/blob/master/mix.exs) 
+ [ ] Run the command `MIX_ENV=test mix sobelow --router lib/auth_web/router.ex` in pre-commit hook?
+ [ ] Run the command on Travis-CI to confirm there are no issues in PRs
