### ISSUE TITLE
How to create/publish an Elixir package on Hex.pm

### ISSUE THREAD

**Issue by nelsonic** [dwyl/learn-elixir#95]
We don't have a beginner-friendly write-up for creating Hex.pm packages; we need a _concise_ guide.

# Todo:

Consolidate these:
+ [x] https://hex.pm/docs/publish
+ [x] https://ieftimov.com/writing-elixir-library
+ [x] http://whatdidilearn.info/2018/06/17/publishing-elixir-packages-to-hex.html
+ [x] https://medium.com/kkempin/how-to-create-and-publish-hex-pm-package-elixir-90cb33e2592d
+ [x] https://medium.com/blackode/how-to-write-elixir-packages-and-publish-to-hex-pm-8723038ebe76
+ [x] Re-position the section _after_ learning syntax https://github.com/dwyl/learn-elixir/pull/107/files https://github.com/dwyl/learn-elixir#publishing

### How to _Use_ the Package Locally _Before_ Publishing it to `hex.pm`

+ https://stackoverflow.com/questions/28185003/using-a-package-locally-with-hex-pm

**Comment by nelsonic** [comment]
# Create a Mix Project and Run Elixir Code
https://pragmaticstudio.com/tutorials/create-elixir-mix-project-and-run-code

This is a good intro to using `mix new` and running the code. 👍

**Comment by nelsonic** [comment]
Continue: 
+ https://github.com/dwyl/learn-elixir/blob/code-reuse-publishing-to-hexpm-issue%2395/code-reuse-hexpm.md
+ https://hexdocs.pm/jason/Jason.html
+ https://davidtang.io/2019/01/22/decoding-json-into-elixir-structs.html

**Comment by nelsonic** [comment]
I think I'm making good progress with this but it's _way_ more work than I anticipated.
I've written 4k words (_which I will need to edit down significantly_) and learned some stuff along the way.
For example: 
TIL: Margaret Hamilton, director of the Software Engineering Division of the MIT Instrumentation Laboratory, which developed on-board flight software for NASA's Apollo space program.
(_one of the people who coined the term "software engineering"_)
https://en.wikipedia.org/wiki/Margaret_Hamilton_(software_engineer)
Not only do Ladies `code` they were _responsible_ for the software for the Nasa Apollo program! 🚀

**Comment by nelsonic** [comment]
![Karl-Pilkington-quote-glass-houses](https://user-images.githubusercontent.com/194400/66721019-511d6a80-edfa-11e9-8a0a-907aea0f0c3e.png)

**Comment by nelsonic** [comment]
Tomorrow:
+ [ ] apply property based testing to `Quotes.random`
see: https://github.com/dwyl/learn-property-based-testing

**Comment by nelsonic** [comment]
Attempting to follow https://github.com/dwyl/learn-property-based-testing and apply it.
Getting the following error: ` ExUnitProperties is not loaded`
```
== Compilation error in file test/quotes_test.exs ==
** (CompileError) test/quotes_test.exs:3: module ExUnitProperties is not loaded and could not be found
    (elixir) expanding macro: Kernel.use/1
    test/quotes_test.exs:3: QuotesTest (module)
    (elixir) lib/kernel/parallel_compiler.ex:237: anonymous fn/4 in Kernel.ParallelCompiler.spawn_workers/7
```

**Comment by nelsonic** [comment]
Had to add 
```elixir 
      {:stream_data, "~> 0.4.2", only: :test} # property based testing
```
to `mix.exs` 📝

**Comment by nelsonic** [comment]
Decided I didn't _need_ to introduce the complexity at this stage. 😕 
Wrote my own recursive function to test all properties in `quotes.json` ✅ 

Meanwhile I've found a way of testing `Quotes.random()` using the Brithday Paradox! 😉 
https://betterexplained.com/articles/understanding-the-birthday-paradox/
![image](https://user-images.githubusercontent.com/194400/66760264-a52b5c00-ee99-11e9-9263-314a54ba1ae9.png)

**Comment by nelsonic** [comment]
Lovely docs for _free_!:
![quotes-docs](https://user-images.githubusercontent.com/194400/66772514-cea5b100-eeb4-11e9-9f79-244847381dcf.png)

**Comment by nelsonic** [comment]
See: https://hex.pm/packages/quotes

![quotes-hex.pm-published](https://user-images.githubusercontent.com/194400/66844523-54ce0000-ef66-11e9-8301-499b8cb14d71.png)

Docs: https://hexdocs.pm/quotes/Quotes.html

![quotes-hexdocs](https://user-images.githubusercontent.com/194400/66844615-7fb85400-ef66-11e9-8cee-e79c210e177b.png)

**Comment by nelsonic** [comment]
# TIL: how to pass a function as a parameter in Elixir:
https://stackoverflow.com/questions/22562192/how-do-you-pass-a-function-as-a-parameter-in-elixir


Use `&Module.function/arity` to pass it, and `.(…)` to call it.

For example:

```elixir
def my_hof(f) # "hof" = higher order function (in case you're wondering...)
    f.([1, 2, 3], &(&1 * 2))
end

my_hof(&Enum.map/2)
```

in my example I modified the code from:
```elixir
  # This recursive function calls Quotes.random until a quote is repeated
  def get_random_quote_until_collision(random_quotes_list) do
    random_quote = Quotes.random()
    if Enum.member?(random_quotes_list, random_quote) do
      random_quotes_list
    else
      get_random_quote_until_collision([random_quote | random_quotes_list])
    end
  end

  test "Quotes.random returns a random quote" do
    # execute Quotes.random and accumulate until a collision occurs
    random_quotes_list = get_random_quote_until_collision([])
    # this is the birthday paradox at work! ;-)
    # IO.inspect Enum.count(random_quotes_list)
    assert Enum.count(random_quotes_list) < 200
  end
```

To:

```elixir
  # This recursive function calls Quotes.random until a quote is repeated
  def get_random_quote_until_collision(random_quotes_list, f) do
    random_quote = f.()
    if Enum.member?(random_quotes_list, random_quote) do
      random_quotes_list
    else
      get_random_quote_until_collision([random_quote | random_quotes_list], f)
    end
  end

  test "Quotes.random returns a random quote" do
    # execute Quotes.random and accoumlate until a collision occurs
    random_quotes_list = get_random_quote_until_collision([], &Quotes.random/0)
    # this is the birthday paradox at work! ;-)
    # IO.inspect Enum.count(random_quotes_list)
    assert Enum.count(random_quotes_list) < 200
  end
```

**Comment by nelsonic** [comment]
I've written 5k words in https://github.com/dwyl/learn-elixir/blob/code-reuse-publishing-to-hexpm-issue%2395/code-reuse-hexpm.md and https://github.com/dwyl/quotes and I feel it's _close_ to being finished ...  but I need to work on something **`else`** for a bit ...

# `#brb`

**Comment by nelsonic** [comment]
Used the `quotes` package in  https://github.com/dwyl/phoenix-content-negotiation-tutorial so I think we can consider this tutorial complete. Assigning the PR to @SimonLab #146 🙏

**Comment by nelsonic** [comment]
# GOTO: [/code-reuse-hexpm.md](https://github.com/dwyl/learn-elixir/blob/master/code-reuse-hexpm.md)
